package capitulo10;

//public class ExceptionDemo {
//     static void compute(int a) throws Exception {
//        System.out.println("Called compute (" + a + ")");
//        if (a > 10)
//            throw new MyException(a);
//         System.out.println("Normal exite");
//    }
//
//    public static void main(String[] args) {
//        try {
//            compute(1);
//            compute(20);
//        }catch (Exception e){
//            System.out.println("Caught " + e);
//        }
//    }
//}
