package capitulo10;
// Demonstração throw.
//public class ThrowDemo {
//    static void demoproc(){
//        try {
//            throw new NullPointerException("demo");
//        }catch (NullPointerException e){
//            System.out.println("Preso dentro do demoproc");
//            throw e; // relança a exceção
//        }
//    }
//    public static void main(String[] args) {
//     try {
//         demoproc();
//     }catch (NullPointerException e){
//         System.out.println("Recapturado: " + e);
//     }
//    }
//}
